[package]
name = "lnx-vfs"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2"
tracing = "0.1"
i2o2 = "0.3"

tokio = { version = "1", features = ["rt", "time", "sync"] }

[dev-dependencies]
tracing-subscriber = "0.3"

fail = { version = "0.5", features = ["failpoints"] }
i2o2 = { version = "0.3", features = ["fail"] }
tokio = { version = "1", features = ["full"] }