[profile.ci]
fail-fast = false
slow-timeout = { period = "40s", terminate-after = 2 }

[[profile.ci.overrides]]
filter = 'test(/\btest_flaky_/)'
retries = 2

[profile.miri]
fail-fast = false
slow-timeout = { period = "120s", terminate-after = 2 }

[profile.default]
slow-timeout = { period = "10s", terminate-after = 2 }

[[profile.default.overrides]]
filter = 'test(/\btest_flaky_/)'
retries = 2