name: "Tests"

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".idea/**"
  workflow_dispatch:

jobs:
  test-all:
    name: Generate Code Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install sccache-cache
        uses: mozilla-actions/sccache-action@v0.0.9
        with:
          version: "v0.12.0"
      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_RESULTS_URL', process.env.ACTIONS_RESULTS_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@cargo-llvm-cov
      - name: Install nextest
        uses: taiki-e/install-action@nextest

      - name: Generate PR code coverage
        if: github.event_name == 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_NUMBER: ${{ github.event.number }}
          RUST_LOG: debug
          MINIMUM_COVERAGE: 90
          SCCACHE_GHA_ENABLED: on
          RUSTC_WRAPPER: sccache
        run: |
          cargo llvm-cov nextest --profile ci \
            --fail-under-functions $MINIMUM_COVERAGE \
            --fail-under-lines $MINIMUM_COVERAGE \
            --fail-under-regions $MINIMUM_COVERAGE \
            --workspace --features test-huge-pages
          
          echo "# Coverage Summary" >> report.md
          echo "\`\`\`" >> report.md
          cargo llvm-cov report --summary-only >> report.md
          echo "\`\`\`" >> report.md
          
          gh pr comment $PR_NUMBER --create-if-none --edit-last --body-file ./report.md

      - name: Test commit
        if: github.event_name != 'pull_request'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUST_LOG: debug
          SCCACHE_GHA_ENABLED: on
          RUSTC_WRAPPER: sccache
        run: |
          cargo nextest run --profile ci --workspace --features test-huge-pages

  miri-tests:
    name: Generate Code Coverage
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - name: Install nextest
        uses: taiki-e/install-action@nextest
      - name: Run Miri
        run: cargo +nightly miri nextest run --workspace --profile miri